name: Test

on:
  push:
    branches: [ main, test_au ]
  pull_request:
    branches: [ main, test_au ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: true
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
